# Generated by Django 4.2.7 on 2023-12-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса'),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_text',
            field=models.TextField(max_length=100, null=True, verbose_name='Текст запроса'),
        ),
    ]
